### ISSUE TITLE
您好，请问是不是少了pred_inter_utils和pred_recog_inter_utils这两个文件。

### ISSUE THREAD

**Issue by littlesulley** [bcmi220/srl_syn_pruning#1]
File "main.py", line 16, in <module>
    from scorer import eval_train_batch, pruning_eval_data
  File "/home/hanqinghong/SRL/syn/scorer.py", line 3, in <module>
    import pred_inter_utils
ModuleNotFoundError: No module named 'pred_inter_utils'

**Comment by xiuzichen** [comment]
ModuleNotFoundError: No module named 'pred_inter_utils'
I got the same issue, Could you share the method you solve this problem? thank you !
